"""Bulletins and their audio. Audio is served only from the finished files in runs/ (or from S3/R2
when configured); checkpoints and article text in runs/ are never exposed."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from src.api import runs
from src.api.now import _bulletin_summary
from src.audio.assets import ensure_assets

router = APIRouter(tags=["bulletins"])


@router.get("/bulletins")
def list_bulletins(day: date | None = Query(None, alias="date"), lang: str | None = None) -> list[dict]:
    return [_bulletin_summary(b) for b in runs.manifests(day, lang)]


@router.get("/bulletins/{bulletin_id}")
def get_bulletin(bulletin_id: str) -> dict:
    try:
        found = runs.bulletin(bulletin_id)
    except ValueError:
        found = None
    if not found:
        raise HTTPException(404, "No such bulletin")
    return found.model_dump(mode="json")


@router.get("/audio/{path:path}")
def audio(path: str) -> FileResponse:
    """runs/<date>/<block>/<lang>/final/<file>.mp3 only."""
    root = runs.runs_dir().resolve()
    target = (root / path).resolve()
    if not target.is_relative_to(root) or target.suffix != ".mp3" or target.parent.name != "final" or not target.exists():
        raise HTTPException(404, "No such audio")
    return FileResponse(target, media_type="audio/mpeg", headers={"Cache-Control": "public, max-age=31536000"})


@router.get("/station/bed.wav")
def bed() -> FileResponse:
    """The station's own bed (CC0, generated by src/audio/assets.py), played under a looping bulletin."""
    return FileResponse(Path(ensure_assets()["bed"]), media_type="audio/wav",
                        headers={"Cache-Control": "public, max-age=86400"})  # it loops: fetch it once
